#服务端口
server:
  #端口号
  port: 8080
#开发环境 java -jar my-spring-boot.jar --spring.profiles.active=dev
spring:
  profiles:
    active: dev

spring:
  # REDIS (RedisProperties)
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 5000
  #rabbitMq
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: huangyun
#    password: 123456
  #数据库
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/mysql
#    username: root
#    password: 123456
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20


#  mybatis:
#    mapper-locations: classpath:mapping/*.xml

account:
  address: 你说啥
#开发环境使用debug模式
logging:
  level:
    com.my: debug
    org:
      springframework:
        security: DEBUG


#spring boot actuator config
#management:
#  endpoints:
#    web:
#      exposure:
#        include: beans,health,info
#  info:
#    git:
#      mode: full

#canal config
canal:
  username: canal
  password: canal
  cluster: false
  destination: mty
  table_filter: mty.account

#Zookeeper config
zookeeper:
  server: 127.0.0.1:2181


eureka:
  instance:
    metadata-map:
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}